# Generated by Django 5.0.14 on 2026-05-15 15:25

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('PROBLEM', 'Problem')], default='WORKING', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_weather_temperature', models.FloatField(blank=True, null=True)),
                ('last_weather_humidity', models.IntegerField(blank=True, null=True)),
                ('last_weather_code', models.IntegerField(blank=True, null=True)),
                ('last_weather_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
